name: Run Tests on PR
on:
  pull_request:

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Test imports
        run: yarn dist-test
      - name: Run tests
        run: yarn test
      - name: Lint
        run: yarn lint-ci
      - name: Build example app
        run: cd docs/example && yarn install && yarn build
